### ISSUE TITLE
named datasets

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/ggvega#1]
I noticed this when I used the Vega Editor on the "Hello World" spec, that the datasets is not named, and we don't have a reference to the named dataset in the layer:

<img src="https://user-images.githubusercontent.com/2800934/59537638-c44eb880-8ebc-11e9-8902-ff39d33e00bf.png" width="500">

Can you check into this please, @wenyuyangpku?

**Comment by wenyuyangpku** [comment]
Yes, I have added the name property for all dataset. For LayerSpec, if the dataset is valued in the TopLevelSpec, Then the LayerSpec can just use `name` to get the `values`. But, as my understanding, global data can only have one dataset? If the data-00 is valued in the TopLevelSpec, should we value it again in the LayerSpec?

**Comment by ijlyttle** [comment]
As you say, I think we can use [Datasets](https://vega.github.io/vega-lite/docs/data.html#datasets) property to provide a top-layer (named) object, then refer to the name in each layer. Here's an [example](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCh5mY5NigAJZGLHcwAdW4AnMQBM1GyDfR50sZHlh7QECI+eiABgC9AG0NHzBvCJ9IAGVkQnQxOgAZZCVqFj0AVjoARnVomPjE5LNGGyycWWzCoqgABXck1PTMxD08ugAWOqLIJpcyiqqwALoAJj7ouMJkeEZkTxxINzxuWExwnwBfaYgo-pKWtIzR7roATn3ihJbyyo7qm99Bk7bRrt7tiIHm4ceenGUx+xTmCyWelW7g2WyKe1Bhxmx2Sp3aeguAHYXlAUXQHqNZCD6o1-q0zk8wF1pDi-kN8SNKcDabFwYtllA1rDIKCEUUkb88WjznQAGwsu4Awn5WlvVEfSldWqg15kglMyYstmQlZczY8+E3AW3Urk9E4ZUkuKShmA6pi2Vk4WKnqO+nqoGalW47Uc6HrfW8o3e62m505V0hvEe+3XENys2fOjY+Nqxme75W1nzdlQvVw6J86LG3xChUYh1Rm0xsCyTP1OnvCmdSNWhM18Y0qO+vMwwOGxFVsPli0S001utupvmql0S0N9vpnDM7s5nWcvsFiJFiIl3E28M4C71o7VpdgCZXKfy5s4L7X22jFdZnu6zcGwvBrMHkdgC5x79x3PWQClTelD1ned+kXO0xhlVcIT9fMP23L8GzLW8wFyE9kTPWDZBTNsnV-JUHw7L0XzXJD3yDQdAOnEUAA4x3uYDWwXYjMK6cUwNY2Dn3Q18NwDLddjQ09h0wi5mKHPjCQfCD714qUNVAyjEN7ESULEuj0J-KS6C7eiVL0IyOPAkj4KI91z3GNTBKozTuVo-lZJvGdchk4zH0pHDfgTRSKPMuSNWJByNLfLSXOLNzE0pXJCL0oDYOPBTLKgmYYKfdijiE-1nIHVzvIg7CWJM2M0q4wyyNsnLkTy5Dot3WKSqspKQtMudKpnJTrI65dqoQ3NIoKz9dIkhj4uTMqfM6rzgvcpNEugtN+MG9ThuE0bUPG3DJI8tqJvK2s6HmlaLKqjL-NW7KzNyxyRv7Maivaxapr8k1+pOj7VQunrpuU2aBrC+6Iq2p6dpeo64ojezoYnAG+relsrpiLKNR+n0HvB0SIB3Hw91DSaKx47yEdJhaYbvGq1pB+rsfyiGdKhvbiYtQ7WeO2Q7syzj-uW3mbLW1HSwamjCpi4rf2kmaEcxxtkbvK9AfIunBTFqKJeaqXMJF-dkvkwHAop86voE0HNsZ3GwHxg4Wt-PWia5urrr+pMTcFs2XbBBnGq1gn7d1oL4bYx2AvSmnsrVn2wat7S8fEzmqaw4Ok7l7qk3l9HPWj0XffF57Jde5OsVltjc9JN2XQ912vYr2Z881wvteLiCZdihG4c9xXZxrtGbtCrVG+25mi+h1r5ejNis75pMw4HjMh9jv3m4DnWDvrqeUo52ue9IlXaq79Xh6ZhPdsFfSDsdreRXr8OqpnoWo6Xy2V8hsek7b5WybYo-+6rlGkdB5DXXHHJqa9W4OzLvhVOu9k5dDvgvYGL9QFv1Hi3ceDsuod1DhnF0PM4GqxQdRJu78MGf2lt-Yu5M8Etkfl7P+edl4FzIRAzBBlJ54UNkjeB61KZEJASQkeZ8WYX32qMXIjD9ZfUnEbCOB9abEKcqfG2icxFsywtA6U88AFKwIf-L2+imGvxYegthFCDLXy4ZSS8RjK4aOpEAz0diG7MNIWYu268RScINpSIktC9FOOQYI5R1tbaREDh5LRfjsE8ONkEuCfdjGoNMSIj+6ie6SOiXNAJs4AL8NqpPDWwjVHn0+j3duP98K5N6gUtaLjsxuJKeEwmGEDpSKdkDE6Z1u68KSfY465t6ZNJUS0yJIp+mdIRog3Rs56GDNgTHEx7i0nkIycnXIDTrGdQFnAwKOi65KMemEtR5SNnZPtC4++-15ldKGcfEZJyymlkvqMXZZzpm5NLgozORyoBUEsLARg8BuAmEsPHUpoizkQVFN7F5vjOozI0RcA5x194bVAQCoFIKwUQrGV4yksL8khxgR065IpiW9JrOi8KlssXAtBVYPFpz4UaNyFYhFOBbFfISY4kJKx6U4qZeAzxkDMKwo5V9S8PS9mUMmdnJW188qCsZeCkVESCURneay460qvmxLqUmBpyrkCAoZbi9VrTXmEr4SS6UVzZ6+URoa6ufzIAqotf7UV7CZz-guReOFAzk7c15W6j1wqvUarFTOWFkyb42KoabCplYeHUttcMulprsWquZc86RmTFk6q6ZebVQaIKyEpYQ88tSLaYqzeaiNq9vUWKiTg2CSKe41FDfy-59ahVqsjVa8RU1K0fOAvqjtXSaW1r9OGgdTao0+tGHG7ZXLC1lult2jFs6+05steMm1HT416EvKO36yLnVJqnYG1xmazX9tzVCotrUV2coDWejdmFZDyqQbOY1DM52PvSdC38sLS1TN-vq25aaikAd3Z6hdQ62UpuoeOuRljeUGpnVCQD+7NXsxlWO9tl7elfzJb+o9Jr717sHQevQsLN6roDZOr+qLr1Krg9RhDrDm3rJff6y8bHy2JqpdWneSy61ccbTxxdLaJEifWZ89DvrTqYcI8kndUn50yaQz3WFR6mN6uU+cTD-7Y64do-hsAsKtlvsE-qj9Ct2Nhvg9Jjxsm+OgfE0WmsRm4mUPAwq2cm8qPZu4+53TydYU+KlQpgxyaHVP3wS5rTQG1kgfFShu1fioOYdg+Z1z2mIt0ZwLC9T+bi2qeM068rTmYMpbC251Z5jPOZfA8e541WciYfa6FhtRXmu8YyzGgTcXz3JrY2mjjBXUt4ejfJ9rhmsukd-F2n5ioGv9bSy14b8nJW6pveSmJtWgtdEo5xxrA3IXAefVg-blXbnCcCxRzbD65tLqmrVjrAbnuzIrZhkLF2tvvbk4S0bv3kPkaSy2ONfW3uWfm+9f1iWL2TbE9Nu9l3ttDdu+K5Hh3HUVjR7Bbir2aOIZK9ZkjinINdaPNT+Lzme3usK9jjzu2bW2diyj5N0GxNmcx8DhHH2IyvpkfqqHX0+Xbpw6zkHrWr6jaE5u9bLYBeSax-LjnEZ7u+eW7KjhAOyfhcG+z3HMbvMVYnPqn90Olb5cF-DinVnPKjdt8io3zOLPO8R91ttoxuV05OjzqdxumvXfS+b+TYuDsQ+TZOtN6vNOa+F6DrVyOJ2e5lwKuXqeFcLdG45o7FYE-87D1d-FvvSvrog8RovhP6ch8T+XtnkXWoGbs1hlbX7MPnZmynn3Iv2aLc7ydhvf5Ld1bL173Pg+0-V6587EPMKEn2a94wSwTAlDAqeU+irrUvtLbjxsyfp2xtY3MxvrfO-W+U8xJP77y+sH17twGvvdKr+MG3-AXfN399ecX0qxf2Q3dzRSq2z3+U-2-1-0j3-0y11zQ38yDjH1f0vEB0v03y-xvy1yj0pHvxjy6Sf0y1AMq3f0xSgOwLz213p0c2+zXyQJU2JyWjDQoJ-1vys3v0AL12AL03TSrRJ3ANpXIMwOgPYKrypxH1i2V2QLUxYJEMoLn3zzwJr0f310ZxhVP1-XoKENnVYJgJ21wPoy7xpxgRYywUl11TkOvzYJwLgItxi1j1yU2Uw1oOVT0LEKHyp0PzfSIMV1VzXTIN0PkJsKoMMOHyVycNXysKwJCMUOoJTm8NixQMh1XxvUaQ-2CP0JxzsOXTSKY38SD2cP8IDSTxw3cNsM6Q0IQOqUKOMMZzTS+zcMyI8PnzAHv0kOdmSN4OPz13QIyOsKyLNxyOUI6MqxII0J4Mq1KIFXKNCOGPo1GzMN1kwwx2EIGJaKUKMNoPyJr2L3COKMDwgPdVmLiLCJTgIL1y6JLnPyn3bWiNEIqLaTeQZx83PD80pg0J6LePuIUJ00pxs3Bwc1kPX2aMeOtSMNGIRl8ILwOIfyaPWLBOHT0Hv0Yx8N2PHxIIaJ+NiL+KswY1GyuK-iuKxJBIRLmMqK8w73FyDz9WKK6EaIAxONxPEOiwJKcLUPG1IOxMGLb1-BRIz1qOJLE1h0ZNBPJKeOUIcMq0JMpJcO5I2PiPv22LRJlMyz5zuNJJiJ5P+LyNH3ZMxLeJUPhK1IVLOIBP9wTVVPaRWPlMRI0X0zd31Ly1tPFPBJwHaIFIYNyIsKmJdNOPmIX3x0eywQNOIwdzWJNLtN4KlM7nZKYJdAZIwLJP9IpLxwtNMn1SFIEMTP6MjNdKROr2VJkU0NmVKlhMCLKLFJTIlIhPxx9P41hPDKCOTOZM8KJTrPZJ9L12mMgKrNbNaNd3TLXWP3bzlM1IePzPtMEOy0RXZMmO7L9P7M2Or0hLYmhKmi+OI1WObLzOrLdIkM9I+KwVL2Ix7OOL7OKzxL4KIwDzqM5JKjHKOIoCZMvJZLvKt0QKPKDhPID0XNfLbJUJ2ODKDnVNvLPOfIvNN15KDiLK5k7OBKfJfLxm2AAF0NAixIAxB0AABPU1UIbYY0PwFwLwEMJQdAVAXQFYJwFwEQIINnSADASwAAay8EgDwGwrmChEIG4C-zwDUCgAfRWEsGQDsHCUgHSBBRsC-2oBIqtAAA9ZKSQoAAAzRYWwKEOUAAHU0tmhxF8HYs4pWAAEdWB0AlAtAXAtAqB7AlLNBtBKKg0PQ9LOQf8dAvAdhvRwlfBsLFKrRVKjA7AVgtKdLwxnK2KOKHLIATKzKLLnBGBrKwqLK3KVg5ghgwAdBmwwqEAkgHLgBwrDKoATAZLVAoB2BXAHK8gAgPKSRqrCxthaqUK6hIAQUlBVKZKcBgAPKdggA).

A global dataset can contain multiple datasets ([example](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCh5mY5NigAJZGLHcwAdW4AnMQBM1GyDfR50sZHlh7QECI+eiABgC9AG0NHzBvCJ9IAGVkQnQxOgAZZCVqFj0AVjoARnVomPjE5LNGGyycWWzCoqgABXck1PTMxD08ugAWOqLIJpcyiqqwALoAJj7ouMJkeEZkTxxINzxuWExwnwBfaYgo-pKWtIzR7roATn3ihJbyyo7qm99Bk7bRrt7tiIHm4ceenGUx+xTmCyWelW7g2WyKe1Bhxmx2Sp3aeguAHYXlAUXQHqNZCD6o1-q0zk8wF1pDi-kN8SNKcDabFwYtllA1rDIKCEUUkb88WjznQAGwsu4Awn5WlvVEfSldWqg15kglMyYstmQlZczY8+E3AW3Urk9E4ZUkuKShmA6pi2Vk4WKnqO+nqoGalW47Uc6HrfW8o3e62m505V0hvEe+3XENys2fOjY+Nqxme75W1nzdlQvVw6J86LG3xChUYh1Rm0xsCyTP1OnvCmdSNWhM18Y0qO+vMwwOGxFVsPli0S001utupvmql0S0N9vpnDM7s5nWcvsFiJFiIl3E28M4C71o7VpdgCZXKfy5s4L7X22jFdZnu6zcGwvBrMHkdgC5x79x3PWQClTelD1ned+kXO0xhlVcIT9fMP23L8GzLW8wFyE9kTPWDZBTNsnV-JUHw7L0XzXJD3yDQdAOnEUAA4x3uYDWwXYjMK6cUwNY2Dn3Q18NwDLddjQ09h0wi5mKHPjCQfCD714qUNVAyjEN7ESULEuj0J-KS6C7eiVL0IyOPAkj4KI91z3GNTBKozTuVo-lZJvGdchk4zH0pHDfgTRSKPMuSNWJByNLfLSXOLNzE0pXJCL0oDYOPBTLKgmYYKfdijiE-1nIHVzvIg7CWJM2M0q4wyyNsnLkTy5Dot3WKSqspKQtMudKpnJTrI65dqoQ3NIoKz9dIkhj4uTMqfM6rzgvcpNEugtN+MG9ThuE0bUPG3DJI8tqJvK2s6HmlaLKqjL-NW7KzNyxyRv7Maivaxapr8k1+pOj7VQunrpuU2aBrC+6Iq2p6dpeo64ojezoYnAG+relsrpiLKNR+n0HvB0SIB3Hw91DSaKx47yEdJhaYbvGq1pB+rsfyiGdKhvbiYtQ7WeO2Q7syzj-uW3mbLW1HSwamjCpi4rf2kmaEcxxtkbvK9AfIunBTFqKJeaqXMJF-dkvkwHAop86voE0HNsZ3GwHxg4Wt-PWia5urrr+pMTcFs2XbBBnGq1gn7d1oL4bYx2AvSmnsrVn2wat7S8fEzmqaw4Ok7l7qk3l9HPWj0XffF57Jde5OsVltjc9JN2XQ912vYr2Z881wvteLiCZdihG4c9xXZxrtGbtCrVG+25mi+h1r5ejNis75pMw4HjMh9jv3m4DnWDvrqeUo52ue9IlXaq79Xh6ZhPdsFfSDsdreRXr8OqpnoWo6Xy2V8hsek7b5WybYo-+6rlGkdB5DXXHHJqa9W4OzLvhVOu9k5dDvgvYGL9QFv1Hi3ceDsuod1DhnF0PM4GqxQdRJu78MGf2lt-Yu5M8Etkfl7P+edl4FzIRAzBBlJ54UNkjeB61KZEJASQkeZ8WYX32qMXIjD9ZfUnEbCOB9abEKcqfG2icxFsywtA6U88AFKwIf-L2+imGvxYegthFCDLXy4ZSS8RjK4aOpEAz0diG7MNIWYu268RScINpSIktC9FOOQYI5R1tbaREDh5LRfjsE8ONkEuCfdjGoNMSIj+6ie6SOiXNAJs4AL8NqpPDWwjVHn0+j3duP98K5N6gUtaLjsxuJKeEwmGEDpSKdkDE6Z1u68KSfY465t6ZNJUS0yJIp+mdIRog3Rs56GDNgTHEx7i0nkIycnXIDTrGdQFnAwKOi65KMemEtR5SNnZPtC4++-15ldKGcfEZJyymlkvqMXZZzpm5NLgozORyoBUEsLARg8BuAmEsPHUpoizkQVFN7F5vjOozI0RcA5x194bVAQCoFIKwUQrGV4yksL8khxgR065IpiW9JrOi8KlssXAtBVYPFpz4UaNyFYhFOBbFfISY4kJKx6U4qZeAzxkDMKwo5V9S8PS9mUMmdnJW188qCsZeCkVESCURneay460qvmxLqUmBpyrkCAoZbi9VrTXmEr4SS6UVzZ6+URoa6ufzIAqotf7UV7CZz-guReOFAzk7c15W6j1wqvUarFTOWFkyb42KoabCplYeHUttcMulprsWquZc86RmTFk6q6ZebVQaIKyEpYQ88tSLaYqzeaiNq9vUWKiTg2CSKe41FDfy-59ahVqsjVa8RU1K0fOAvqjtXSaW1r9OGgdTao0+tGHG7ZXLC1lult2jFs6+05steMm1HT416EvKO36yLnVJqnYG1xmazX9tzVCotrUV2coDWejdmFZDyqQbOY1DM52PvSdC38sLS1TN-vq25aaikAd3Z6hdQ62UpuoeOuRljeUGpnVCQD+7NXsxlWO9tl7elfzJb+o9Jr717sHQevQsLN6roDZOr+qLr1Krg9RhDrDm3rJff6y8bHy2JqpdWneSy61ccbTxxdLaJEifWZ89DvrTqYcI8kndUn50yaQz3WFR6mN6uU+cTD-7Y64do-hsAsKtlvsE-qj9Ct2Nhvg9Jjxsm+OgfE0WmsRm4mUPAwq2cm8qPZu4+53TydYU+KlQpgxyaHVP3wS5rTQG1kgfFShu1fioOYdg+Z1z2mIt0ZwLC9T+bi2qeM068rTmYMpbC251Z5jPOZfA8e541WciYfa6FhtRXmu8YyzGgTcXz3JrY2mjjBXUt4ejfJ9rhmsukd-F2n5ioGv9bSy14b8nJW6pveSmJtWgtdEo5xxrA3IXAefVg-blXbnCcCxRzbD65tLqmrVjrAbnuzIrZhkLF2tvvbk4S0bv3kPkaSy2ONfW3uWfm+9f1iWL2TbE9Nu9l3ttDdu+K5Hh3HUVjR7Bbir2aOIZK9ZkjinINdaPNT+Lzme3usK9jjzu2bW2diyj5N0GxNmcx8DhHH2IyvpkfqqHX0+Xbpw6zkHrWr6jaE5u9bLYBeSax-LjnEZ7u+eW7KjhAOyfhcG+z3HMbvMVYnPqn90Olb5cF-DinVnPKjdt8io3zOLPO8R91ttoxuV05OjzqdxumvXfS+b+TYuDsQ+TZOtN6vNOa+F6DrVyOJ2e5lwKuXqeFcLdG45o7FYE-87D1d-FvvSvrog8RovhP6ch8T+XtnkXWoGbs1hlbX7MPnZmynn3Iv2aLc7ydhvf5Ld1bL173Pg+0-V6587EPMKEn2a94wSwTAlDAqeU+irrUvtLbjxsyfp2xtY3MxvrfO-W+U8xJP77y+sH17twGvvdKr+MG3-AXfN399ecX0qxf2Q3dzRSq2z3+U-2-1-0j3-0y11zQ38yDjH1f0vEB0v03y-xvy1yj0pHvxjy6Sf0y1AMq3f0xSgOwLz213p0c2+zXyQJU2JyWjDQoJ-1vys3v0AL12AL03TSrRJ3ANpXIMwOgPYKrypxH1i2V2QLUxYJEMoLn3zzwJr0f310ZxhVP1-XoKENnVYJgJ21wPoy7xpxgRYywUl11TkOvzYJwLgItxi1j1yU2Uw1oOVT0LEKHyp0PzfSIMV1VzXTIN0PkJsKoMMOHyVycNXysKwJCMUOoJTm8NixQMh1XxvUaQ-2CP0JxzsOXTSKY38SD2cP8IDSTxw3cNsM6Q0IQOqUKOMMZzTS+zcMyI8PnzAHv0kOdmSN4OPz13QIyOsKyLNxyOUI6MqxII0J4Mq1KIFXKNCOGPo1GzMN1kwwx2EIGJaKUKMNoPyJr2L3COKMDwgPdVmLiLCJTgIL1y6JLnPyn3bWiNEIqLaTeQZx83PD80pg0J6LePuIUJ00pxs3Bwc1kPX2aMeOtSMNGIRl8ILwOIfyaPWLBOHT0Hv0Yx8N2PHxIIaJ+NiL+KswY1GyuK-iuKxJBIRLmMqK8w73FyDz9WKK6EaIAxONxPEOiwJKcLUPG1IOxMGLb1-BRIz1qOJLE1h0ZNBPJKeOUIcMq0JMpJcO5I2PiPv22LRJlMyz5zuNJJiJ5P+LyNH3ZMxLeJUPhK1IVLOIBP9wTVVPaRWPlMRI0X0zd31Ly1tPFPBJwHaIFIYNyIsKmJdNOPmIX3x0eywQNOIwdzWJNLtN4KlM7nZKYJdAZIwLJP9IpLxwtNMn1SFIEMTP6MjNdKROr2VJkU0NmVKlhMCLKLFJTIlIhPxx9P41hPDKCOTOZM8KJTrPZJ9L12mMgKrNbNaNd3TLXWP3bzlM1IePzPtMEOy0RXZMmO7L9P7M2Or0hLYmhKmi+OI1WObLzOrLdIkM9I+KwVL2Ix7OOL7OKzxL4KIwDzqM5JKjHKOIoCZMvJZLvKt0QKPKDhPID0XNfLbJUJ2ODKDnVNvLPOfIvNN15KDiLK5k7OBKfJfLxm2AAF1pg-AXARAAg8hQhvRoLrShyTppCZxLwAhUjtzQk8UIhUKNAixIAxB0AABPU1XC9LDCzAHAYASAJQdAVAXQFYJwTCoISAcJSADASwAAay8EgDwEYrmChEIG4C-zwBEpuEgHSBBRsC-2oC8BDAAA9dKSRfAAAzRYWwKEOUAAHUstmhxF8FkvkpWAAEdWB0AlAtAXAtAqB7AjLNBtB+Kg0PQ7LOQf8dAvAdhvRwlfBGLDKjLIBTKjA7AVgrKbLwxgqZK5KArIAXK3KPLnBGBvL0qPKwqVg5ghgwAdBmx0qEAkgAquKHKsqTAdLVAoB2BXAAq8gAgIqSQoqoAH1OL3UkhWAsrLBkA7BurCxth8ZjR2LpKeK+KoRBLAgcLRLxKpKBqGqFKlL3LVLQR1KlBNLtLYr+gDLOLvQTKzKkqBlrLbLzrNBMqoQcr3LmB8rCq7qZL-KLKF5qrQq6qJrI1orjqGwErzLkr-gbq0r3rNrnLXLnrPKCrdAirPrSr-gKrywfrarpLoaoAmq1BWr2rOgurIraR+rIhBqxBhqoR2AKbdBerVhGAAAvOq8mymu8IIf63YKajQNChwEFJQUynSziiKnYIAA)).

What do you think?

**Comment by wenyuyangpku** [comment]
Yes, you are right. I'm sorry I ignore the `datasets`. Thanks for reminding me. 
For now, I just use an easy way to realize the `datasets`. These days I will try to adjust the code to make it more understandable and robust.
