### ISSUE TITLE
Warning in ggvega

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/ggvega#10]
This appears in the README example:

```r
as_vegaspec(p)
#> Warning in .as_vegaspec.list(spec): Spec has no `$schema` element, adding
#> `$schema` element for Vega-Lite major-version
```

I suspect this falls in @wenyuyangpku's area - Wenyu, can you check into this? If/when there is a fix, following our new protocol, could you make a PR into `master`?

Thanks!

**Comment by wenyuyangpku** [comment]
Oh, that's my fault. I forgot the `$` symbol.  Now it works
