### ISSUE TITLE
ggschema data stucture

### ISSUE THREAD

**Issue by wenyuyangpku** [vegawidget/ggvega#21]
Hi @ijlyttle and @haleyjeppson  ,

When I tried to build `ggschema`, I found it's difficult to define the `data` of `ggSpec`.

For now, the `data` is 
```
data:{
     data-00:{
          metadata:{},
          observations:{}
     },
     data-01:{}
}
```

The question is `data` is not an array but an object. That means I have to define`data-00`, `data-01` and any datasets we may use. To solve this question, I have a tentative solution:

```
data:[
     {
          name:"data-00",
          metadata:{},
          observations:{}
     },
     {
          name:"data-01",
          metadata:{},
          observations:{}
     }
]
```

Then we can describe the `data` by transforming it into an array. 

We have a similar question on our `metadata`.  For now, it's
```
metadata:{
     Sepal.Length:{
           type:"quantitative"
     },
     Species:{
           type:"nominal",
           level:[]
     }
}
```
`Sepal.Length` and `Species` are variabal rather than the properties of `metadata`. Maybe it's a better way to transform `metadata` into an array like this:
```
metadata:[
     {
           name:"Sepal.Length",
           type:"quantitative"
     },
     {
           name:"Species",
           type:"nominal",
           level:[]
     }
]
```

Because I'm not really familiar with json-schema, I'm not sure can we build `ggschema` if we don't change the  `ggSpec`. Maybe you can give me some advice. As my understanding, all properties should be defined in json-schema and we should avoid some variable like `data-00` and `Sepal.Length` being properties. 

Looking forward your guidance in our next meeting.

**Comment by ijlyttle** [comment]
This is a good question. My first thought is that we should leave open the possibility to change what we are doing with ggspec, along the lines that you suggest.

I found this example in Vega-Lite which seems to do the same sort of thing as we propose:

https://vega.github.io/vega-lite/docs/data.html#datasets

```json
    "datasets": {
      "somedata": [1,2,3]
    },
    "data": {
      "name": "somedata"
    }
```

Here, an element is named `"somedata"`, which is an arbitrary name. 

Can you look to see what Vega-Lite does in this case with its schema?

**Comment by wenyuyangpku** [comment]
Very thanks for your reminder.  I think I find the solution and we don't need to change `ggspec`.
