### ISSUE TITLE
Travis testing of Typescript

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/ggvega#27]
Given that @wenyuyangpku's tests are in TypeScript, I'd like to find a way for Travis to run those tests, in addition to running the R tests.

**Comment by wenyuyangpku** [comment]
Here is the link of ggvega TS test: [wenyuyangpku/ggvega](https://github.com/wenyuyangpku/ggvega).

Hope to help you.

**Comment by ijlyttle** [comment]
Thanks - fixed in f080e14efd9a6ce472a628fd5b367200006e6d23, will close this issue when it merges into `master`

**Comment by ijlyttle** [comment]
done in #30
