### ISSUE TITLE
spec validation

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/ggvega#29]
This would apply to both ggspec and Vega-Lite

The validator we think to use, ajv, emits a *lot* of messages. It would be nice if we could provide more-targeted feedback.

Consider the link to the Vega-Editor, below; it has an error.

There are two feedback mechanisms:

1. Detailed feedback on the lower-right; this seems like the ajv feedback, noisy and imprecise.

2. In the code editor itself, there seems to be more-precise feedback, showing the offending 
tag, precisely.

@wenyuyangpku, there is no rush on this, but could you look into the mechanisms that the editor is using to provide the feedback (particularly (2.)), and see if we could use?

---

https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOChL0qZNih4ATsjETYAfXboDY5AE81GyABNkCA40J4eKnJAAqKGB+RiaMsGBOYYRi6LZg7HEAQsjwANbIBmDIeGDoYnRgKGKEyE5ZsHjo7KaIYLAYJmCorGJe0a654ehggDgEhNwA7hkAZi1NKYjoSmGoYMPcmaxKLgYVU5FK1GCMSngZ6PBeyuE7dXiskR3cw4WDuWBGsP1KsMgRyCXL4cpZAB7RU3QeAWcQoVkYVRssEAuAQFAASGTeQweHwM3CcrHgb26hmMpjA1zAiSsNjitkYxic4WGaNmLDeAEYAJzSAAMsFUYHg3FQ7T2YAGzFqGB2ImQw2GKTw3wMKx2W2BcwOjAklX53N54MUSjoDggziBmBwwEgrGsegNlVIlmsdnk2sgAF91PqMAZUhb+js8HqoNyxKxUC89AAmF1QZBKbkbah6UAQfXDA7ZOMaBNQYYUsROC2wSS+9OQPC2EoWhYbPIFhOQRQGH3GyDcQgWnSRKZqDNZnO+cmUp1psDOgeQX7SVPp-XoajUIy0PYt0oQlThwuZvs9rtV-XF0u+ACOrCmXjVjCoW6gCDyugbAC8Mtw9EmxK9HQOh4X7MaB4nN74we5snsFdqx3a8oHLHZK2A-Va3rMATUjaN5QtX4O0bWUMgtFwEEjGMnWgi94CvONIAMKZqGQABlPZmxwBkQ1fdN32rf0FhItdswtWxkCsNDQItJQeUgsR+wgZjSNcbgxDPBtLxsEjUN8HYXE+FxdjQz8oGUj5cMjH1HVfR0gA

**Comment by ijlyttle** [comment]
A question that follows a discussion @wenyuyangpku and I had Tuesday afternoon (2019-07-30):

In ggvega, when we use ajv to validate the incoming ggspec, will an invalid ggspec throw an error?

The reason I ask this is to ask about the log-based validation that comes later - just to make sure that we would reach that code to generate those log statements.

**Comment by wenyuyangpku** [comment]
Yes. For now, ajv throws `error` and stops working. But I will change them to `warning` today (maybe these days) and we can use log-based validation to validate the ggSpec.

And like vega-lite, I believe our log-based validation should have both `warning` and `error`. If the problem is vital, ggvega should throw an error.

**Comment by ijlyttle** [comment]
Let's close this, and collapse into #33
