### ISSUE TITLE
Functions to translate values for shape/size/color

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/ggvega#3]
I know we will have a larger issue of agreeing on the rules to translate these between ggspec and Vega-Lite, but I think a useful first step will be to have these isolated as their own functions (maybe even in their own file) in the ggvega TypeScript project. 

Apologies if @wenyuyangpku has already done this, I am catching up from last-week's meeting.

**Comment by wenyuyangpku** [comment]
Yes, I have rewritten the functions and files. Here is an example to translate the `encoding`
```
export function TranslateEncoding(layer: any, labels: any, layerData: any, scales: any): vlspec.LayerEncoding {
  const layerEncoding: vlspec.LayerEncoding = {
    x: TranslateXClass(layer, labels, layerData, scales),
    y: TranslateYClass(layer, labels, layerData, scales),
    // color: TranslateColor(layer, labels, layerData),
    size: TranslateSize(layer, labels, layerData),
    shape: TranslateShape(layer, labels, layerData),
    stroke: TranslateStroke(layer, labels, layerData),
    strokeWidth: TranslateStrokeWidth(layer, labels, layerData),
    opacity: TranslateOpacity(layer, labels, layerData),
    fill: TranslateFill(layer, labels, layerData)
  };

  return layerEncoding;
}
```

**Comment by ijlyttle** [comment]
Hi Wenyu,

Looking forward to looking at these functions in more-detsizeail - what I had in mind was functions that translate the *value* size/shape/color from ggplot2 to Vega-Lite.

For example a value for size of `2` in ggplot2 might translate to a value for size of `60` in Vega-Lite; similar for shape and color. 

It was these specific translations I was interested in having dedicated functions.
