### ISSUE TITLE
location of constant-valued mappings

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/ggvega#4]
When, for example, color is constant (`"red"`), this is currently implemented as:

```json
"mark": {"type": "point", "color": "red"}
```

I think this should be implemented as:

```json
"mapping" : {
  "color": {"value" : "red"}
}
```

I think this will make it easier to implement conditional mappings when we start to think about interactivity.

**Comment by wenyuyangpku** [comment]
Do you mean:
```
"encoding" : {
  "color": {"value" : "red"}
}
````

If yes, I will move the `aes_params` to the `encoding`. I think all `aes_params` like `color`, `size`, `opacity` , `fill`, `stroke`, `shape` should move to `encoding`?

**Comment by ijlyttle** [comment]
Yes, I mean `encoding` 😳

I think, for now, all `aes_params` should go into `encoding`, using `value`.

**Comment by wenyuyangpku** [comment]
I have removed all `aes_params` into `encoding`
