### ISSUE TITLE
About renaming to lowercase

### ISSUE THREAD

**Issue by wenyuyangpku** [vegawidget/ggvega#41]
Hi @ijlyttle ，

This is a personal question.

When I try to rename TS file to lowercase, I found the git cannot catch this change. For example, I rename `Encoding.ts` to `encoding.ts`. The Rstudio and Git cannot find the difference.  Do you have any solutions?

**Comment by ijlyttle** [comment]
Hi @wenyuyangpku,

There seem to be a couple possibilities: 

- a workaround where you change to a temporary name: <https://stackoverflow.com/a/6899682>
- perhaps the git configuration could be changed for a more-robust solution: <https://stackoverflow.com/a/31393409>

**Comment by wenyuyangpku** [comment]
Thanks, I will close this #41
