### ISSUE TITLE
File organization in ggschema

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/ggvega#43]
Hi @wenyuyangpku, 

Could we establish a branch/PR where we just reorganized the content of ggschema classes?

For example, as a first thought, I would like to have a file each for `Geom`, `Stat`, and `Scale`.

I'd be happy to discuss further, but I would like to use the "reorganized" ggschema files as the starting point for me to add/modify classes in anticipation of incorporating stats in a layer (see #42). This would give us a chance to see if I understand ggschema well enough to make changes.

Of course, once I have proposed something for ggschema, they would not be accepted unless/until we all agree.

**Comment by ijlyttle** [comment]
This reference on cherry-picking files from a branch may be useful: https://jasonrudolph.com/blog/2009/02/25/git-tip-how-to-merge-specific-files-from-another-branch/

**Comment by wenyuyangpku** [comment]
Hi @ijlyttle and @haleyjeppson ,

I have created a new branch [schema-update](https://github.com/vegawidget/ggvega/tree/schema-update)  and a new pull request #46 .

Before you merge this branch, I will never edit `ggschema`. If I need, I will work on this new branch and use cherry-picking to transfer the changes. 

Whenever you have any confusion or question on json-schema and typescript, please ask me. I hope I can help you.

**Comment by ijlyttle** [comment]
Hi @wenyuyangpku, I see what you are saying. 

I will propose some changes to this branch then, if it makes sense, they can be merged back into `refactor-TS`.

At a point where `refactor-TS` is working, perhaps we can `merge` it into `master`, as a way for us to be able to propose updates to ggschema. 

I think that you could continue work in `refactor-TS`, so that we could finish the refactoring, then merge again `refactor-TS` into `master`.

What do you think?

**Comment by ijlyttle** [comment]
Done
