### ISSUE TITLE
Get TS working again

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/ggvega#53]
Issue to solve for #52

**Comment by ijlyttle** [comment]
@wenyuyangpku,

I remember you had suggested using cacheing to speed up the yarn builds. I came across [this](https://docs.travis-ci.com/user/caching/#yarn-cache):

> ```yaml
> language: node_js
>
> node_js: '6' # or another
>
>cache: yarn
```

It seems to me that this will work only for node projects, we are already set up as an R project.

There has been [discussion](https://github.com/travis-ci/travis-ci/issues/4090) on Travis supporting multiple-language projects, but I don't think it is possible yet.

**Comment by ijlyttle** [comment]
One other question for this issue: do you think it could be possible to change the name of `src-ext/Typescript` to `src-ext/TypeScript`?

**Comment by wenyuyangpku** [comment]
Hi @ijlyttle，

I agree with you. We can keep our test.

I think you can change the name to `src-ext/TypeScript`. Can you help me do it? Because I'm not confidential on the up/lowercase things. I think it will not impact the TypeScript code.

**Comment by ijlyttle** [comment]
No problem, I have renamed to `src-ext/TypeScript`.
