### ISSUE TITLE
Difficulty extending ggschema

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/ggvega#61]
I am working in the `stat` branch, trying to extend ggschema.

I am running into a couple of problems, perhaps we can look at them sequentially:

- [x] When ggvega builds, it does not recognize `ggschema/src/layerPosition.ts` as a module. I have added this file to extend ggschema to include `position`. See [travis log](https://travis-ci.org/vegawidget/ggvega/jobs/571836685#L726).
- [x] I get a validation warning when I try to extend `Geom` to include both `GeomPoint` and `GeomBar`. When I comment out the `| GeomBar`, I don't get the warning.

https://github.com/vegawidget/ggvega/blob/6843224d0626f7bb5d188b43a713dafa277afa56/src-ext/TypeScript/ggschema/src/layerGeom.ts#L1

@wenyuyangpku - when you get a chance, could you take a look?

Thanks!

**Comment by wenyuyangpku** [comment]
Hi @ijlyttle ，

Is your `layerPosition.ts` empty? As a module, you have to output something.

**Comment by ijlyttle** [comment]
Let's work on the first question for now. I think my problem for `layerPosition.ts` was that I did not save it - and I did not recognize that in VS Code - my fault.

Now that I have saved it, I have two different problems:

- on my Mac, I `yarn build` ggschema, `yarn build` ggvega, "Build & Install" the package, then run `test()` from R. 
  
  I get a warning from ggvega:

  ```
  test-translate.R:93: warning: spec2vl works
  ggSpec.layers[0] should NOT have additional properties
  ```

  This warning does not appear (but other errors appear, as I would expect) if I remove

  ```json
      "position": {
        "class": "PositionIdentity"
      },
  ```

  from `tests/examples/ggspec/scatterplot-iris.json`.

- on Travis, I get a completely (what appears to be) a completely different [set of errors](https://travis-ci.org/vegawidget/ggvega/jobs/571908760#L1064).

**Comment by wenyuyangpku** [comment]
Hi @ijlyttle ,

- The first question：

The warning is because you haven't used `position` in your ggschema. 

```
export interface BaseLayer {
  data: string;
  mapping: Mapping;
  aes_params: AesParams;
  position: Position;
}
```

After that, you have to edit the `PositionIdentity`. Remove the `position`.   
```
export interface PositionIdentity {
  class: 'PositionIdentity';
}
```

And when you remove `position` from tests/examples/ggspec/scatterplot-iris.json. You face an error from `gg2spec`. I think you know the reason.

- The second question:

That's because you have edited the ggschema. The examples in tests are not longer  GG.TopLevelSpec types. You have to update the examples. Or you can change the type of examples from `GG.TopLevelSpec` to `any` temporarily. These examples should be in `ggvega/test/ggSpec.ts`

**Comment by ijlyttle** [comment]
Augh! This comes from the same place - I can't seem to recognize when I have not saved something in VS Code. 😫

Thanks for your patience, let me try some more...

**Comment by ijlyttle** [comment]
I think I might have sorted this out, thanks to your advice. Waiting for Travis to let me know...

**Comment by ijlyttle** [comment]
Back to green and working consistently with my Mac! Thanks @wenyuyangpku!
