### ISSUE TITLE
README example not working on Travis

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/ggvega#8]
Hi @wenyuyangpku, I think this might be related to 6c52258f37c2ec6bfeecdf79f10fae64d5ed7371, where you switch over to the Vega-Lite source code. 

The README example works on my copy of ggvega, which does not yet have this update.

Here's the Travis build: https://travis-ci.org/vegawidget/ggvega/jobs/551592631

Can you look into this?

I think this may give us a starting point for testing and using feature-branches.

I don't know if this is related or not, but if you are using the VL source code, what steps can we take to make sure that the VL source code matches the VL version we are supporting in vegawidget?

**Comment by ijlyttle** [comment]
Today, we determined that V8 with the "new" code works on MacOS and Windows (@haleyjeppson - could you confirm on your Windows machine?) but does not work on Linux (Travis or RStudio Cloud).

(Aside to Wenyu, you might look into getting a free [RStudio Cloud account](https://rstudio.cloud) as it would let you use a Linux machine interactively, but no sudo)

Here's an article at the release of the latest V8: https://ropensci.org/technotes/2019/02/11/v8-20/

Interesting quote:

> If you write R packages with JS bindings, note that some Linux systems will still be running the legacy 3.14 engine for now. Hence to release the package on CRAN, you still need to use a fallback polyfill or transpile your modern JS to traditional JS something like babel.js to support legacy ES5 engines.

I understand this to mean that V8 on Linux systems still use ES5, whereas V8 on MacOS and Windows use ES6. I thought that this might be what's happening to us. So I made an experiment:

```r
ct <- V8::v8()
ct$eval("let x = 2;") # this expression uses ES6
```

When I ran this on MacOS, it worked; When I ran it on RStudio Cloud:

```
Error in context_eval(join(src), private$context) : 
  SyntaxError: Unexpected identifier
```

This looks familiar....

So I think this is our problem. Vega-Lite uses ES6 (as of version 3).

---

As we discussed in our call:

- I think that we should put `master` back to the "old" way for now, using the spec. 
- Let's put the "new" way in a feature branch.

We don't plan to introduce any new features in the next little while, so this may give @wenyuyangpku a little time to investigate. I am a JavaScript outsider, so please evaluate these suggestions accordingly.

Question for @wenyuyangpku: In the "old" way, were you transpiling your code to be ES5 compatible?

If so, does TypeScript offer a way to transpile something like Vega, which has already been compiled?

On my end, if I run into Joeren Ooms (V8 author), I'll ask him about this to see when he thinks the Linux V8 might be updated, or to ask him if he has any ideas on workarounds.

---

Finally, I tag in @AliciaSchep and @sa-lee because they have all sorts of JS experience, and may have some words of enlightenment. (Thanks!)

**Comment by wenyuyangpku** [comment]
Hi @ijlyttle and @haleyjeppson 

The `ggvega` has rolled back to the vega-lite schema version. And we also has a branch [vegalite-source-code https://github.com/vegawidget/ggvega/tree/vl-source-code](https://github.com/vegawidget/ggvega/tree/vl-source-code).

**Comment by ijlyttle** [comment]
Thanks @wenyuyangpku! 

I will close this issue and open another to discuss the `vl-source-code` version branch.
